[tool.black]
line-length = 120
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | \{{cookiecutter.reponame}}
    | _build
    | build
    | dist
  )/
)
'''
