{# raw is for ignoring templating with cookiecutter, leaving it for use with conda-build #}
{% raw -%}
{% set pyproject = load_file_data('pyproject.toml') %}
{% set pproject = pyproject.get('project', {}) %}
{% set python_requirement = pproject.get('requires-python') %}
{%- endraw %}

package:
  name: {{ cookiecutter.package_name }}
  {% raw -%}
  version: {{ pproject.get('version') }}
  {%- endraw %}

source:
  path: ..

build:
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    {% raw -%}
    # dependencies defined in pyproject.toml
    - python{{ python_requirement }}
    {% for dep in pproject.get('dependencies', []) %}
    - {{ dep.lower() }}
    {% endfor %}
    {%- endraw %}

test:
  imports:
    - {{ cookiecutter.package_name }}
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest tests

about:
  home: TODO
  summary: {{ cookiecutter.project_short_description }}
